### ISSUE TITLE
Save not working

### ISSUE THREAD

**Issue by mgcrea** [aurora/rmate#13]
Not sure what I may have done wrong (followed this: http://danieldemmel.me/blog/2012/09/02/setting-up-rmate-with-sublime-text-for-remote-file-editing-over-ssh/), using a custom 2224 port.

Opening remote files works perfectly but `ctrl-s` in sublime text 2 does not impact the remote file. Any idea what might be going on?

**Comment by aurora** [comment]
I don't think that this is an rmate issue.
