### ISSUE TITLE
Does not support the +N syntax and cannot be used as $EDITOR

### ISSUE THREAD

**Issue by cyril-bouthors** [aurora/rmate#47]
rmate does not support the +N syntax which is supposed to place caret on line number after loading file, just like --line:

```
$ ./rmate +3 /etc/fstab
There is more than one file specified. Opening only +3 and ignoring other.
```

Others editors like vi, emacs, mg support this, even nano:

```
emacs +3 /etc/fstab
vi +3 /etc/fstab
nano +3 /etc/fstab
mg +3 /etc/fstab
```

I prevents some program like 'debchange' to work:

```
$ export EDITOR='rmate -w'
$ debchange -i
There is more than one file specified. Opening only +3 and ignoring other.
```

and SublimeText opens the file called "+3"

Would it be possible to support +N as an alias to --line=N?

Thank you

PS: sorry about my initial bug report, I apparently triggered a shortcut to open the ticket before it was done

**Comment by aurora** [comment]
I think this should be easy to implement. I'll have a look at it, thanks for your suggestion.

**Comment by aurora** [comment]
Could you have a look at my latest commit? I think it should work now what you would like to do.

**Comment by cyril-bouthors** [comment]
@aurora,

The latest commit seems to be working but the caret stays on line 1.

Same issue with 

rmate --line 3 /tmp/x

<img width="437" alt="screen shot 2016-03-15 at 18 50 36" src="https://cloud.githubusercontent.com/assets/1205360/13782013/d3fac664-eade-11e5-9061-46d15ae3116f.png">

**Comment by aurora** [comment]
mmm ... i have to admit that i only tested with textmate ... i'll have a look at sublime later today.

**Comment by aurora** [comment]
It does not seem to be possible with sublime text. at least: the subl command of sublime text itself does not offer a `--line` option, either ... ?

**Comment by cyril-bouthors** [comment]
The syntax is FILE:LINE_NUMBER, example:

```
subl /etc/hosts:2
```

**Comment by aurora** [comment]
Apparently i misunderstood how things work with sublime text. Sublime text is using the rsub package to achieve the remote editing functionality. So in my opinion a fix for the problem would belong to this package. As i am not the author of rsub, there's not much that i can do. But i'll have a look at it and maybe i can provide a patch for it ...

**Comment by cyril-bouthors** [comment]
Thanks
On Thu, Mar 17, 2016 at 2:07 PM Harald Lapp <notifications@github.com>
wrote:

> Apparently i misunderstood how things work with sublime text. Sublime text
> is using the rsub package to achieve the remote editing functionality. So
> in my opinion a fix for the problem would belong to this package. As i am
> not the author of rsub, there's not much that i can do. But i'll have a
> look at it and maybe i can provide a patch for it ...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aurora/rmate/issues/47#issuecomment-197800924>
>
-- 
Cyril Bouthors - go-managed.com <http://www.go-managed.com/>
 +33-1-84-16-16-17
https://www.linkedin.com/in/cyrilbouthors

**Comment by aurora** [comment]
@cyril-bouthors i think i have a working patch for this, as i don't know how fast the original author of rsub is, you can fetch the change from my rsub fork at https://github.com/aurora/rsub in the meantime.

**Comment by cyril-bouthors** [comment]
Great!

On Thu, Mar 17, 2016 at 5:38 PM Harald Lapp <notifications@github.com>
wrote:

> @cyril-bouthors <https://github.com/cyril-bouthors> i think i have a
> working patch for this, as i don't know how fast the original author of
> rsub is, you can fetch the change from my rsub fork at
> https://github.com/aurora/rsub in the meantime.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/aurora/rmate/issues/47#issuecomment-197882634>
>
-- 
Cyril Bouthors - go-managed.com <http://www.go-managed.com/>
 +33-1-84-16-16-17
https://www.linkedin.com/in/cyrilbouthors
