### ISSUE TITLE
browse project folder

### ISSUE THREAD

**Issue by scher200** [aurora/rmate#51]
@dhowden Waauw I really like this project, especially rmate.sh because it runs almost everywhere.
I viewed the code and realized for the first time how to use tcp in bash.
Do you think it is possible to not only edit a file but also browse the folder over the tunneled ssh port in sublimetext?

**Comment by aurora** [comment]
Glad you like it :). I've learned a lot about bash coding during development, too.

I think it will not be possible to have a fully functional folder-browser, but at least opening multiple files was proposed multiple times and there are also two open pull-requests https://github.com/aurora/rmate/pulls which add this functionality. However, i am still undecided if this is really the way to go ... and haven't had much time to work on my own approach, either :(

**Comment by aurora** [comment]
I am going to close this now, folder browsing is not possible and i merged #46 for opening multiple files.
