### ISSUE TITLE
version_date should probably be the same as date of release

### ISSUE THREAD

**Issue by aslakr** [aurora/rmate#62]
This https://github.com/aurora/rmate/blob/v0.9.9/rmate#L37 now says:

```bash
version="0.9.9"
version_date="2017-04-06"
```

I suppose it should be:

```bash
version="0.9.9"
version_date="2017-06-27"
```

or something similar.

**Comment by aurora** [comment]
Yep, you are right -- i forgot to bump the date before tagging :-( ... but maybe it's time to bump to version 1.0.0 anyway ... :-)

**Comment by aurora** [comment]
Fixed!
