### ISSUE TITLE
Add docs for other editors

### ISSUE THREAD

**Issue by hadisfr** [aurora/rmate#69]
While this project has originally targeted _TextMate_, I think it's not bad to add necessary links or short guides to use it with other editors, using e.g. [rsub for Sublime Text](https://github.com/henrikpersson/rsub), [RemoteSubl for Sublime Text](https://github.com/randy3k/RemoteSubl) or [remote-atom for Atom](https://github.com/randy3k/remote-atom) to [README.md](https://github.com/aurora/rmate/blob/master/README.md).

**Comment by aurora** [comment]
Sure, i am totally open to this. Can you provide a pull-request? I do not want to add this myself because i am not really familiar with other editors.

**Comment by hadisfr** [comment]
I'm using sublime myself. I try to add something about sublime when I've got some free time.
But about atom, I don't now. Adding something based on docs of [remote-atom for Atom](https://github.com/randy3k/remote-atom) may be better than nothing. What's your opinion?

**Comment by hadisfr** [comment]
There's something about Sublime now.

remote-atom for Atom [is no longer supported](https://github.com/randy3k/remote-atom#maintainer-wanted), so I didn't write anything about it.

**Comment by hadisfr** [comment]
And perhaps we should update [wiki](https://github.com/aurora/rmate/wiki).

Also, <http://dl.dropbox.com/u/5014780/github/rmate/Irix%20Session.png> has been deleted and [wiki/Screens](https://github.com/aurora/rmate/wiki/Screens) is useless now. I couldn't find that picture from net.

**Comment by hadisfr** [comment]
[Wiki/Home](https://github.com/aurora/rmate/wiki/Home) is updated now.
