### ISSUE TITLE
Flags specified after the file-to-open are ignored

### ISSUE THREAD

**Issue by fake-name** [aurora/rmate#73]
```
durr@testcnc:~$ rmate /usr/lib/tcltk/linuxcnc/bin/halshow.tcl
File /usr/lib/tcltk/linuxcnc/bin/halshow.tcl is not writable! Use -f to open anyway.
durr@testcnc:~$ rmate /usr/lib/tcltk/linuxcnc/bin/halshow.tcl -f
File /usr/lib/tcltk/linuxcnc/bin/halshow.tcl is not writable! Use -f to open anyway.
durr@testcnc:~$ rmate -f /usr/lib/tcltk/linuxcnc/bin/halshow.tcl
< file opens >
```

For shell commands, I generally assume that flags can go anywhere. However, rmate seems to only parse arguments `rmate <here> filename`. 

This is, well, certainly unexpected, if not a huge issue. It'd be nice if arguments to `rmate` behaved like every other well-behaved command-line tool.

**Comment by aurora** [comment]
Mmmm ... thanks for the suggestion, i'll have a look into this.

**Comment by aurora** [comment]
I've created a branch for this and i think i fixed it - could you give it a try?

**Comment by aurora** [comment]
I've merged this into the master branch, because i think it's fixed now.

**Comment by fake-name** [comment]
Cool! Sorry, I haven't had a chance to poke at it yet.
