### ISSUE TITLE
v1.0.2 raises a syntax error; v1.0.1 works

### ISSUE THREAD

**Issue by roussanoff** [aurora/rmate#81]
I recently had to set up my remote server again. The newly-downloaded rmate stopped working. I get the following error:

```
[user@log-1 ~]$ rmate example.txt
~/bin/rmate: line 81: syntax error near unexpected token `$home/."${0##*/}.rc"'
~/bin/rmate: line 81: `$home/."${0##*/}.rc"; do'
```

If I use v1.0.1 from Jan 8, 2018, I do not get this error and my Sublime Text successfully opens `example.txt`.

I am not an experienced user in shell scripting. I can provide more information if necessary.

**Comment by aurora** [comment]
sorry for the late reply ... mmm ... i am unable to reproduce this, 1.0.2 runs quite fine for me. I am not sure, how to track this issue down; could you insert a `echo $home` just before the `for` loop in row 80 and tell me the output? thanks!
